### ISSUE TITLE
the video work but sometime they get an error message

### ISSUE THREAD

**Issue by Deadlydarty** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#195]
### What happened?

covering the video this error also happen on other browsers

### Platform

Extension

### Version

2.4.6

### What browser are you on?

Chrome

### Browser version

114.0.5735.199

### Screenshots or Videos

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/128548152/e0456633-5c99-4d0b-b3ef-d63b451e1d02)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, I see you are using an older version. This is fixed in the latest version [v2.5.7](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.7).

**Comment by obnys** [comment]
Hi =)
I'm sorry but this error persists in v2.5.7 using Firefox v115.0.2.

**Comment by drunkwinter** [comment]
> Hi =)
> I'm sorry but this error persists in v2.5.7 using Firefox v115.0.2.

Any chance you could provide a screenshot of the developer console? In any way I will be investigating when I get the chance.

**Comment by drunkwinter** [comment]
@obnys Also is the error code you get the same as the above? If not, can you file a separate report?

**Comment by obnys** [comment]
Sorry I didn't mention. Yes, the error code was exactly the same. That's why I didn't port a separate report.

**Comment by drunkwinter** [comment]
> Sorry I didn't mention. Yes, the error code was exactly the same. That's why I didn't post a separate report. @drunkwinter Could you pls tell me how to open up the dev console and which data I need to pay attention to for the screenshot?

F12 and filter for `Simple-YouTube-Age-Restriction-Bypass`.

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/38593134/53a1f605-69bc-4d0f-a1fa-acc95c00c570)

**Comment by drunkwinter** [comment]
@obnys I have tried everything I could, but I still am not able to reproduce your issue. Just to be sure, can you confirm you are on the latest version and you don't have a duplicate install?

**Comment by drunkwinter** [comment]
It would have made sense if it wasn't working because of the old version of the extension, but this surprises me. Have you tried on other browsers?

**Comment by obnys** [comment]
I just tried with Chrome and I found the issue. OMFG, this is so emberrassing... My sincere apologies for wasting your time. Tampermonkey was deactivated and FF was using the old Addon's v2.5.4 -.-
![grafik](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/42369895/e6c25346-5c93-4b40-9041-9bcfd6a38a68)

**Comment by drunkwinter** [comment]
> I just tried with Chrome and I found the issue. OMFG, this is so emberrassing... My sincere apologies for wasting your time. Tampermonkey was deactivated and FF was using the old Addon's v2.5.4 -.- ![grafik](https://user-images.githubusercontent.com/42369895/255671332-e6c25346-5c93-4b40-9041-9bcfd6a38a68.png)

It's no problem, glad you figured it out ;)

@Deadlydarty Did updating to a newer version help also? Might close this issue as this problem seems to be fixed already in latest versions.

**Comment by Deadlydarty** [comment]
the new verison you give me work ty
